spring.application.name=Spring_Security

server.port=8080

spring.datasource.url=jdbc:postgresql://localhost:5432/New
spring.datasource.username=postgres
spring.datasource.password=Redmi1234@@@@

logging.level.org.springframework.security=debug


# Enable component scanning for the entire 'com.project' package
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.main.allow-bean-definition-overriding=true

# Ensure JPA repositories are scanned
spring.data.jpa.repositories.enabled=true


jwt.secret=Y7Ax1WPOPDNaLD9UL/php7i8Ma7InBaQqp2ODPu63+s=

# 10 minutes in milliseconds
jwt.expiration-time=600000  
# 20 minutes in milliseconds (20 * 60 * 1000)
jwt.refresh-expiration-time=1200000  